version: 0.2
            
phases:
  pre_build:
    commands:
      - make setup-environment
  build:
    commands:
      # Copy code to folder, which works with go dep
      - mkdir -p ${HOME}/go/src/github.com/auto-staging/ec2-demo
      - mv $CODEBUILD_SRC_DIR/* ${HOME}/go/src/github.com/auto-staging/ec2-demo
      - export CODEBUILD_SRC_DIR=${HOME}/go/src/github.com/auto-staging/ec2-demo
      - export GOPATH=${HOME}/go

      - cd $CODEBUILD_SRC_DIR
      - make build
artifacts:
  base-directory: ${HOME}/go/src/github.com/auto-staging/ec2-demo
  files:
    - bin/*
    - static/css/*
    - templates/*
    - scripts/*
    - appspec.yml
    - systemd/auto-staging-ec2-demo.service
