version: 0.2
            
phases:
  pre_build:
    commands:
      - make setup-environment
  build:
    commands:
      - make build
artifacts:
  files:
    - bin/*
    - static/css/*
    - templates/*
    - scripts/*
    - appspec.yml
    - systemd/auto-staging-ec2-demo.service
